### ISSUE TITLE
Small bug in `preprocess_train_dev_data.py`

### ISSUE THREAD

**Issue by whwang299** [taoyds/syntaxSQL#3]
Just a small bug. 
At line 12, 13, `train_dev` variable is used before declaration.

Thanks for sharing you guys great work!

**Comment by YuxiangLu** [comment]
you can simply add a line: train_dev = "dev" before it used to solve this question.

**Comment by YuxiangLu** [comment]
> Just a small bug.
> At line 12, 13, `train_dev` variable is used before declaration.
> you can simply add a line: train_dev = "dev" before it used to solve this question.
> Thanks for sharing you guys great work!

**Comment by YuxiangLu** [comment]
> Just a small bug.
> At line 12, 13, `train_dev` variable is used before declaration.
> 
> Thanks for sharing you guys great work!

you can simply add a line: train_dev = "dev" before it used to solve this question.

**Comment by taoyds** [comment]
thanks @YuxiangLu

**Comment by geislern** [comment]
I disagree.

This solution renders the entire if case unnecessary; the script will always work on the dev set.

IMHO lines 12 and 13 need to be moved between lines 17 and 18.

It looks like someone tried to clean up the code by moving the assignment containing a path closer to the TODO, but did not take into account, that those two if statements depend on each other.
