### ISSUE TITLE
Performance on real life applications?

### ISSUE THREAD

**Issue by Spenhouet** [taoyds/syntaxSQL#5]
As far as I can see your work shows results for cross domain tasks with an accuracy of 27.2% on the test set.

While in the context of this research work the results seem impressive I wonder how that transfers to the real life.
The goal of cross domain learning is to learn from one domain to finally improve in a target domain.
What I'm looking for is to apply this model on a real life database, use the cross domain knowledge and **refine it to perform well on the real life database**.
I'm missing the last part in this work.
To be a successfull cross domain learning model wouldn't you need to show performance results on a unknown database (test set) as WikiSQL? Or is your performance on this database also about 27.2%? If so, then your performance would be far off from the current leading 83.6%.

What I'm asking is: Is there a way to use the syntaxSQL model, use the cross domain knowledge and refine it for a target database (for example for WikiSQL)?

If this is not possible I wonder if this work has any real life application. An accuracy of 27.2% is totally unusable for a real life application. Or do I totally miss something?

**Comment by taoyds** [comment]
Sorry for such a late reply. SQL queries in WikiSQL dataset contain only SELECT and WHERE clauses. All of them are simple. Instead, Spider dataset is much more complicated, which covers almost all SQL components including nested queries, GROUP BY, ORDER BY, JOIN etc. This means our task is much challenging. We are in the early research stage in this field. Once the performance goes up to around 70% on Spider task, it might be possible to have a system performing well on the real-life database (still definitely have many other problems).
