### ISSUE TITLE
How to regenerate generated_datasets/generated_data_augment?

### ISSUE THREAD

**Issue by rshin** [taoyds/syntaxSQL#6]
README.md states

> If you would like to run data augmentation by yourself, first download `wikisql_tables.json` and `train_patterns.json` from [here](https://drive.google.com/file/d/1DZCITYsy9oXjayY1I2e4Wk1nfxUa_oiG/view?usp=sharing), and then run ```python generate_wikisql_augment.py``` to generate more training data.

which creates files with names like `data_augment/1-23937219-2.txt`. However, there does not appear to be any code for reading these files in `preprocess_train_dev_data.py` so they can be preprocessed and output into `generated_data_augment`. How can we reproduce this step?

**Comment by taoyds** [comment]
I uploaded those scripts. Please try them out.
