### ISSUE TITLE
I was wondering whether you could provide the augment data which is similar to train_spider.json

### ISSUE THREAD

**Issue by ygan** [taoyds/syntaxSQL#7]
I will get 2198380 SQL and NL pairs if I run **‘generate_wikisql_augment.py’** and **‘get_data_wikisql.py’**. But you only used 98000 of these pairs mentioned on your paper.    
I was wondering whether you could provide the augment data which is similar to **train_spider.json** or **train_other.json** in **spider**. Because, I can create the training dataset through **preprocess_train_dev_data.py** but it is hard to get the original json dataset from [generated_dataset](https://drive.google.com/file/d/1FHEcceYuf__PLhtD5QzJvexM7SNGnoBu/view).  
Thank you.

**Comment by taoyds** [comment]
I updated the download link for data_augment (https://drive.google.com/file/d/13I_EqnAR4v2aE-CWhJ0XQ8c-UlGS9oic/view?usp=sharing). You can find **train_wikisql.json** in the folder.

**Comment by ygan** [comment]
Thank you so much!!!
